# Generated by Django 3.2.5 on 2022-02-26 17:10

import apps.products.validators
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('index', models.PositiveIntegerField(default=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True)),
                ('rgt', models.PositiveIntegerField(db_index=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True)),
                ('depth', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='OptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('index', models.PositiveIntegerField(default=1000000)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name/ Value')),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('display_symbol', models.CharField(blank=True, max_length=5)),
                ('sku_symbol', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('option_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_type', to='products.optiontype')),
            ],
            options={
                'verbose_name': 'Option Value',
                'verbose_name_plural': 'Option Values',
                'order_with_respect_to': 'option_type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('sku_symbol', models.CharField(max_length=5, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_price_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('min_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZAR', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))])),
                ('max_price_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('max_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZAR', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))])),
                ('min_price_original_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('min_price_original', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZAR', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))])),
                ('max_price_original_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('max_price_original', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZAR', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))])),
                ('is_form_validated', models.BooleanField(default=False)),
                ('brands', models.ManyToManyField(blank=True, to='products.Brand')),
                ('categories', models.ManyToManyField(related_name='products', to='products.Category')),
                ('option_types', models.ManyToManyField(blank=True, related_name='option_types', to='products.OptionType')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='products.product')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SupplierNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Note',
                'verbose_name_plural': 'Supplier Notes',
                'order_with_respect_to': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('selling_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZAR', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))])),
                ('discounted_price_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('discounted_price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='ZAR', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))])),
                ('percentage_discount', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[apps.products.validators.validate_percentage_discount])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sku_no', models.CharField(max_length=30, unique=True)),
                ('is_form_validated', models.BooleanField(default=False)),
                ('option_values', models.ManyToManyField(blank=True, related_name='product_variants', to='products.OptionValue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.supplier')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'order_with_respect_to': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Product Note',
                'verbose_name_plural': 'Product Notes',
                'order_with_respect_to': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a product image', upload_to='img/product-images')),
                ('index', models.PositiveIntegerField()),
                ('alt_text', models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative Text')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_option_value_icon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('option_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.optionvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'order_with_respect_to': 'product',
            },
        ),
        migrations.CreateModel(
            name='OptionTypeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('option_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.optiontype')),
            ],
            options={
                'verbose_name': 'Option Type Note',
                'verbose_name_plural': 'Option Type Notes',
                'order_with_respect_to': 'option_type',
            },
        ),
        migrations.CreateModel(
            name='CategoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Category Note',
                'verbose_name_plural': 'Category Notes',
                'order_with_respect_to': 'category',
            },
        ),
        migrations.CreateModel(
            name='CategoryHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a category image', upload_to='apps/products/static/products/img/categories')),
                ('index', models.PositiveIntegerField()),
                ('alt_text', models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Category Hero Image',
                'verbose_name_plural': 'Category Hero Images',
                'order_with_respect_to': 'category',
            },
        ),
        migrations.CreateModel(
            name='BrandNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
            options={
                'verbose_name': 'Brand Note',
                'verbose_name_plural': 'Brand Notes',
                'order_with_respect_to': 'brand',
            },
        ),
    ]
