# Generated by Django 3.2.5 on 2022-03-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_optiontype_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('position',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='optiontype',
            options={'ordering': ('position',), 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='index',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='categoryheroimage',
            old_name='index',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='optiontype',
            old_name='index',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='index',
            new_name='position',
        ),
    ]
