# Generated by Django 3.2.5 on 2022-03-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220319_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='percentage_discount',
        ),
    ]
