# Generated by Django 3.2.5 on 2022-03-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productvariant_percentage_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='headline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
