# Generated by Django 3.2.5 on 2022-06-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220605_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionvalue',
            name='display_symbol',
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='display_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
