# Generated by Django 3.2.5 on 2022-09-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220612_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.ProductType'),
        ),
    ]
