# Generated by Django 3.2.5 on 2022-09-29 12:12

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Deleted')], default=1),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='selling_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='ZAR', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))]),
        ),
    ]
