# Generated by Django 3.2.5 on 2022-10-02 09:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220929_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='selling_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZAR', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='ProductThumbnailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a product image', upload_to='img/product-thumbnail-images')),
                ('position', models.DecimalField(decimal_places=30, default=Decimal('1000000'), max_digits=40)),
                ('alt_text', models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative Text')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_option_value_icon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('option_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.optionvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_thumbnail_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Thumbnail Image',
                'verbose_name_plural': 'Product Thumbnail Images',
                'order_with_respect_to': 'product',
            },
        ),
    ]
