# Generated by Django 3.2.5 on 2022-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20221002_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku_symbol',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku_no',
            field=models.CharField(max_length=30),
        ),
    ]
