# Generated by Django 3.2.5 on 2022-02-26 17:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_registered_checkout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('approx_speed', models.CharField(max_length=1000)),
                ('approx_cost_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('approx_cost', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZAR', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Shipping Method',
                'verbose_name_plural': 'Order Shipping Methods',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('town_city', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('awaiting_scheduling', 'Awaiting setting of shipping date and other details'), ('scheduled', 'A shipping date and other mandatory details have been set'), ('awaiting_pickup', 'Awaiting pickup'), ('shipped', 'Order is out for shipping')], default='awaiting_scheduling', max_length=32)),
                ('shipping_method_pk', models.TextField()),
                ('shipping_method_name', models.CharField(max_length=1000)),
                ('speed', models.CharField(max_length=1000)),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZAR', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('paid', 'Fully paid for'), ('cancelled', 'Payment cancelled')], default='awaiting_payment', max_length=32)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_delivery', 'Awaiting delivery'), ('delivered', 'Delivered and signed for')], default='awaiting_delivery', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pk', models.CharField(max_length=1000000)),
                ('product_name', models.CharField(max_length=100)),
                ('product_variant_pk', models.CharField(max_length=1000000)),
                ('option_values', models.CharField(blank=True, max_length=10000, null=True)),
                ('selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('selling_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZAR', max_digits=19)),
                ('discounted_price_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('discounted_price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='ZAR', max_digits=19, null=True)),
                ('percentage_discount', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sku_no', models.CharField(max_length=30)),
                ('order_item_quantity', models.PositiveIntegerField()),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('ZAR', 'Rand')], default='ZAR', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZAR', max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Line Item',
                'verbose_name_plural': 'Order Line Items',
                'order_with_respect_to': 'order',
            },
        ),
    ]
