# Generated by Django 3.2.5 on 2022-02-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contact_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffphonenumber',
            name='staff_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_phone_numbers', to='users.staffprofile'),
        ),
        migrations.AddField(
            model_name='staffaddress',
            name='staff_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_addresses', to='users.staffprofile'),
        ),
        migrations.AddField(
            model_name='guestcustomerphonenumber',
            name='guest_customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_customer_phone_numbers', to='users.guestcustomerprofile'),
        ),
        migrations.AddField(
            model_name='guestcustomeraddress',
            name='guest_customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_customer_addresses', to='users.guestcustomerprofile'),
        ),
        migrations.AddField(
            model_name='customerphonenumber',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_phone_numbers', to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to='users.customerprofile'),
        ),
    ]
